// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS6QU1UcsIiEDAdqvyEeETvlgJkOtyB0A',
    appId: '1:315987608342:web:d1533a36291d2b3d31c637',
    messagingSenderId: '315987608342',
    projectId: 'device-streaming-52f6dc32',
    authDomain: 'device-streaming-52f6dc32.firebaseapp.com',
    storageBucket: 'device-streaming-52f6dc32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2cwGFLRP6wB8uUN-EUSA7FpnRnpiFusM',
    appId: '1:315987608342:android:469d064806b403a531c637',
    messagingSenderId: '315987608342',
    projectId: 'device-streaming-52f6dc32',
    storageBucket: 'device-streaming-52f6dc32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs5I6P4ib4QkAvzCH7KWgXQxkMP1IkCEE',
    appId: '1:315987608342:ios:8f3e574e150acac831c637',
    messagingSenderId: '315987608342',
    projectId: 'device-streaming-52f6dc32',
    storageBucket: 'device-streaming-52f6dc32.firebasestorage.app',
    iosBundleId: 'com.example.chatatan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs5I6P4ib4QkAvzCH7KWgXQxkMP1IkCEE',
    appId: '1:315987608342:ios:8f3e574e150acac831c637',
    messagingSenderId: '315987608342',
    projectId: 'device-streaming-52f6dc32',
    storageBucket: 'device-streaming-52f6dc32.firebasestorage.app',
    iosBundleId: 'com.example.chatatan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS6QU1UcsIiEDAdqvyEeETvlgJkOtyB0A',
    appId: '1:315987608342:web:e9cf41ee4c94c86931c637',
    messagingSenderId: '315987608342',
    projectId: 'device-streaming-52f6dc32',
    authDomain: 'device-streaming-52f6dc32.firebaseapp.com',
    storageBucket: 'device-streaming-52f6dc32.firebasestorage.app',
  );
}
